### ISSUE TITLE
CMI Holograms

### ISSUE THREAD

**Issue by Wgis** [thetealviper/Spigot_ChatBubbles#5]
Hello, can you add support for [CMI](https://www.zrips.net/cmi/api/) holograms?
If you need some tests, we can do it with Discord. Wgis#0932

**Comment by thetealviper** [comment]
Responding from far in the future for sake of closing the issue and responding publicly/officially: I will not be adding CMI support because it costs money and I simply don't feel like purchasing it. I also don't support piracy against the dev's wishes so people stop offering to "send me it" 😂 Unless the dev themself adds me to their Spigot purchase list or delivers the jar by hand, CMI support will not even be a consideration (though I understand why people want it).
